# Generated by Django 3.0.5 on 2020-04-18 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=64), size=None
            ),
        )
    ]
